import {faker} from 'ember-cli-mirage';

export const gridOptions = {
  columnDefs: [
    { headerName: "Product", field: "name" },
    { headerName: 'Jan', field: 'jan' },
    { headerName: 'Feb', field: 'feb' },
    { headerName: 'Mar', field: 'mar' },
    { headerName: 'Apr', field: 'apr' },
    { headerName: 'May', field: 'may' },
    { headerName: 'Jun', field: 'jun' },
    { headerName: 'Jul', field: 'jul' },
    { headerName: 'Aug', field: 'aug' },
    { headerName: 'Sep', field: 'sep' },
    { headerName: 'Oct', field: 'oct' },
    { headerName: 'Nov', field: 'nov' },
    { headerName: 'Dec', field: 'dec' }

  ],
  rowData: [
    {
      name: faker.commerce.productName,
      jan: faker.commerce.price,
      feb: faker.commerce.price,
      mar: faker.commerce.price,
      apr: faker.commerce.price,
      may: faker.commerce.price,
      jun: faker.commerce.price,
      jul: faker.commerce.price,
      aug: faker.commerce.price,
      sep: faker.commerce.price,
      oct: faker.commerce.price,
      nov: faker.commerce.price,
      dec: faker.commerce.price
    },
    {
      name: faker.commerce.productName,
      jan: faker.commerce.price,
      feb: faker.commerce.price,
      mar: faker.commerce.price,
      apr: faker.commerce.price,
      may: faker.commerce.price,
      jun: faker.commerce.price,
      jul: faker.commerce.price,
      aug: faker.commerce.price,
      sep: faker.commerce.price,
      oct: faker.commerce.price,
      nov: faker.commerce.price,
      dec: faker.commerce.price
    },
    {
      name: faker.commerce.productName,
      jan: faker.commerce.price,
      feb: faker.commerce.price,
      mar: faker.commerce.price,
      apr: faker.commerce.price,
      may: faker.commerce.price,
      jun: faker.commerce.price,
      jul: faker.commerce.price,
      aug: faker.commerce.price,
      sep: faker.commerce.price,
      oct: faker.commerce.price,
      nov: faker.commerce.price,
      dec: faker.commerce.price
    },
    {
      name: faker.commerce.productName,
      jan: faker.commerce.price,
      feb: faker.commerce.price,
      mar: faker.commerce.price,
      apr: faker.commerce.price,
      may: faker.commerce.price,
      jun: faker.commerce.price,
      jul: faker.commerce.price,
      aug: faker.commerce.price,
      sep: faker.commerce.price,
      oct: faker.commerce.price,
      nov: faker.commerce.price,
      dec: faker.commerce.price
    },
    {
      name: faker.commerce.productName,
      jan: faker.commerce.price,
      feb: faker.commerce.price,
      mar: faker.commerce.price,
      apr: faker.commerce.price,
      may: faker.commerce.price,
      jun: faker.commerce.price,
      jul: faker.commerce.price,
      aug: faker.commerce.price,
      sep: faker.commerce.price,
      oct: faker.commerce.price,
      nov: faker.commerce.price,
      dec: faker.commerce.price
    },
    {
      name: faker.commerce.productName,
      jan: faker.commerce.price,
      feb: faker.commerce.price,
      mar: faker.commerce.price,
      apr: faker.commerce.price,
      may: faker.commerce.price,
      jun: faker.commerce.price,
      jul: faker.commerce.price,
      aug: faker.commerce.price,
      sep: faker.commerce.price,
      oct: faker.commerce.price,
      nov: faker.commerce.price,
      dec: faker.commerce.price
    },
    {
      name: faker.commerce.productName,
      jan: faker.commerce.price,
      feb: faker.commerce.price,
      mar: faker.commerce.price,
      apr: faker.commerce.price,
      may: faker.commerce.price,
      jun: faker.commerce.price,
      jul: faker.commerce.price,
      aug: faker.commerce.price,
      sep: faker.commerce.price,
      oct: faker.commerce.price,
      nov: faker.commerce.price,
      dec: faker.commerce.price
    }
  ],
};